# Automatically determine number of workers based on available CPU cores
worker_processes auto;

# Maximum connections per worker
events
{
	worker_connections 1024;
}

http
{
	# MIME types for correct content serving
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	# Http
	server
	{
		listen 80;
		listen [::]:80;

		# Resolve both root and www subdomain
		server_name ${domain} www.${domain};

		# Redirect http traffic to https
		location /
		{
			return 301 https://$host$request_uri;
		}
	}

	# Https
	server
	{
		listen 443 ssl;
		listen [::]:443 ssl;

		# Resolve both root and www subdomain
		server_name ${domain} www.${domain};

		# Root directory and root files
		root /var/www/html/;
		index index.php index.html index.htm;

		# Use faster http protocol and hide Nginx version
		http2 on;
		server_tokens off;

		# SSL certificates
		ssl_certificate /etc/ssl/inception_ella-peeters_me/inception_ella-peeters_me.crt;
		ssl_certificate_key /etc/ssh/ella-peeters.me.key;
		ssl_trusted_certificate /etc/ssl/inception_ella-peeters_me/inception_ella-peeters_me.ca-bundle;

		# Enforce strong cipher suite and secure TLS protocols, preferring newer version
		ssl_ciphers HIGH:!aNULL:!MD5;
		ssl_protocols TLSv1.3 TLSv1.2;

		# Handle PHP requests via FastCGI for WordPress
		location ~ \.php$
		{
			# Connect FastCGI to WordPress over port 9000
			fastcgi_pass wordpress:9000;
			include fastcgi_params;
			fastcgi_index index.php;
			fastcgi_split_path_info ^(.+\.php)(/.+)$;
			fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
			fastcgi_param PATH_INFO $fastcgi_path_info;
			
			# Send FastCGI errors to the default Nginx error log
			error_log /var/lib/nginx/logs/error.log;
		}

		# Main WordPress handling, routing non-static requests to WordPress
		location /
		{
			try_files $uri /index.php?$args;
		}

		# Serve static files with caching
		location ~* \.(css|js|png|jpg|jpeg|gif|ico|woff|woff2|ttf|eot|otf|svg)$
		{
			try_files $uri =404;
			expires max;
			access_log off;
		}

		# Serve WordPress assets with caching
		location ~* ^/wp-includes/.*\.(css|js|png|jpg|jpeg|gif|ico|woff|woff2|ttf|eot|otf|svg)$
		{
			try_files $uri =404;
			expires max;
			access_log off;
		}

		# Deny access to hidden files
		location ~ /\.
		{
			deny all;
		}
	}
	# Log requests and errors
	access_log /dev/stdout;
	error_log /dev/stderr;
}
