version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - inception

  inception:
    image: nginx
    volumes:
      - ./app:/usr/share/nginx/html:ro
    expose:
      - "8000"
