version: '3.7'

services:
  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./static:/var/www/html:ro
      - /etc/ssl/inception_ella-peeters_me:/etc/ssl/inception_ella-peeters_me:ro
      - /home/lpeeters/.ssh/ella-peeters.me.key:/etc/ssh/ella-peeters.me.key:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  #inception:
    #image: nginx:latest
    #container_name: inception
    #expose:
      #- "8000"
